### ISSUE TITLE
error line 49

### ISSUE THREAD

**Issue by partylikeits1983** [keizerzilla/telegram-chat-parser#1]
Traceback (most recent call last):
  File "parser.py", line 50, in <module>
    for message in jdata["messages"]:
KeyError: 'messages'

**Comment by keizerzilla** [comment]
Hi. A new version was updated today. Please check if that works for you. Also thank you for pointing out the error.

**Comment by partylikeits1983** [comment]
I realized that I was trying to parse the result.json that was generated for all telegram messages. I made a pull request to enable this functionality. This way users don't have to export all chats individually.

**Comment by keizerzilla** [comment]
PR done, nice addition
