### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by jjones3286** [keizerzilla/telegram-chat-parser#3]
Hi, 

I am having quite a lot of issues getting this script to run. 

When invoking the script to run, the following error is returned:

```
File "d:\Scripts\Python\telegram-chat-parser\telegram-chat-parser.py", line 43, in <module>
    available_chat_names = [chat['name'] for chat in telegram_export['chats']['list'] if ('name' in chat) and chat['name'] != None]
KeyError: 'chats'
```
Do you have a fix for this?

**Comment by keizerzilla** [comment]
Hi @jjones3286. I will work on a fix for that, but right now I'm a little busy. I will ping you again once it's done. Also thanks for pointing out the error.

**Comment by keizerzilla** [comment]
@jjones3286 I've updated the script (also the README). Please try it out and ping me if something is still wrong.

**Comment by jjones3286** [comment]
Thanks so much!! It works perfectly!
