### ISSUE TITLE
CSV file format to included a column "is_forwarded"

### ISSUE THREAD

**Issue by zhuoriley** [keizerzilla/telegram-chat-parser#5]
Hi,

I'm wondering if it is possible to add a column in the output csv file which will reflect on whether a message is forwarded from somewhere within Telegram. 

For example, if a messages is forwarded into the chat from somewhere on Telegram, that message will be tagged 1 in that column and if the message is not forwarded but an original message from the user it will be tagged 0.

I've tried adding a few lines to the existing script but I'm not sure the exact attribute that represents "is_forwarded" to use.

**Comment by keizerzilla** [comment]
Hi, @zhuoriley, and thank you for the message.

I think that would be a great addition. Right now I'm stuck with my job, but I will try to find some time in the upcoming weekend to take a look. I will keep this thread updated with what I found.

**Comment by zhuoriley** [comment]
Hi there 😊

I found a way to include a column "forwarded_name" which is essentially the variable "forwarded_from" in the json file.
I thought it might be more useful to have the name of the owner of the message besides 0 and 1. We can definitely build on that to have the is_forwarded column if needed.

Thanks!
[telegram-chat-parser2.txt](https://github.com/keizerzilla/telegram-chat-parser/files/10790442/telegram-chat-parser2.txt)

**Comment by keizerzilla** [comment]
Hey! It's been a while, but I finally managed to code this feature. Thank you!

The main branch has been updated.
